#!/usr/bin/env python3
"""Regenerates include/secrets.h from OTA_PASSWORD in ".env" before every
build (wired in via platformio.ini's `extra_scripts = pre:`, so this runs
for USB builds/uploads and the OTA env alike, including from the VSCode
PlatformIO IDE buttons - not just through tools/ota_upload.py). This gives
OTA_PASSWORD exactly one place to be set instead of two gitignored files
that had to be kept in sync by hand.

Falls back to an already-exported OTA_PASSWORD env var if set, same
precedence tools/ota_upload.py already uses.
"""
import os
import sys

# PlatformIO execs pre-build scripts via SCons' SConscript() rather than
# running/importing them normally, so there is no `__file__` to derive the
# project directory from - it's available as env["PROJECT_DIR"] on the
# SCons construction environment PlatformIO passes in instead. Fall back to
# __file__ when run directly (e.g. `python tools/sync_secrets.py` by hand),
# where Import()/env don't exist at all.
try:
    Import("env")
    PROJECT_DIR = env["PROJECT_DIR"]
except NameError:
    PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ENV_FILE = os.path.join(PROJECT_DIR, ".env")
SECRETS_FILE = os.path.join(PROJECT_DIR, "include", "secrets.h")

TEMPLATE = """#pragma once

// Auto-generated by tools/sync_secrets.py from OTA_PASSWORD in ".env" -
// do not edit by hand, edit .env instead (copy from .env.example). Both
// files are gitignored either way.

// Used ONLY for OTA flashing (ArduinoOTA) - see CLAUDE.md "BLE
// configuration" for how everything else (WiFi, inverter IP, BLE/web
// passwords) is provisioned instead.
#define OTA_PASSWORD        "{password}"
"""


def load_env_file(path):
    values = {}
    if not os.path.isfile(path):
        return values
    with open(path, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            values[key.strip()] = value.strip()
    return values


def main():
    password = os.environ.get("OTA_PASSWORD") or load_env_file(ENV_FILE).get("OTA_PASSWORD")
    if not password:
        sys.stderr.write(
            "sync_secrets.py: OTA_PASSWORD not set. Copy .env.example to "
            ".env and fill it in, or export OTA_PASSWORD directly.\n"
        )
        sys.exit(1)

    content = TEMPLATE.format(password=password)
    if os.path.isfile(SECRETS_FILE):
        with open(SECRETS_FILE, "r") as f:
            if f.read() == content:
                return

    os.makedirs(os.path.dirname(SECRETS_FILE), exist_ok=True)
    with open(SECRETS_FILE, "w") as f:
        f.write(content)


main()
