#!/usr/bin/env python3
"""Regenerates include/build_info_stamp.h before every build (wired in via
platformio.ini's `extra_scripts = pre:`, alongside tools/sync_secrets.py, so
this runs for USB builds/uploads and the OTA env alike, including from the
VSCode PlatformIO IDE buttons).

The stamp is what lets the HTTP control page notice it's running against
newer firmware than the shell it loaded, and reload itself - see
solar_control.cpp's handle_root()/build_status_json() and PAGE_HTML's
build_id check. It has to change on every build for that to work, so unlike
sync_secrets.py this deliberately does NOT skip the write when the previous
contents differ only by timestamp - there is no "unchanged" case.

Only src/build_info.cpp includes the generated header, so rewriting it every
build costs one small recompile plus a relink, not a full rebuild.
"""
import os
import subprocess
import time

# PlatformIO execs pre-build scripts via SCons' SConscript() rather than
# running/importing them normally, so there is no `__file__` to derive the
# project directory from - it's available as env["PROJECT_DIR"] on the
# SCons construction environment PlatformIO passes in instead. Fall back to
# __file__ when run directly (e.g. `python tools/sync_build_info.py` by
# hand), where Import()/env don't exist at all.
try:
    Import("env")
    PROJECT_DIR = env["PROJECT_DIR"]
except NameError:
    PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STAMP_FILE = os.path.join(PROJECT_DIR, "include", "build_info_stamp.h")

TEMPLATE = """#pragma once

// Auto-generated by tools/sync_build_info.py on every build - do not edit,
// and don't include this directly: go through include/build_info.h so only
// src/build_info.cpp has to recompile when the stamp changes.

#define FIRMWARE_BUILD_STAMP "{stamp}"
"""


def git(*args):
    """Best-effort `git` call. Returns "" on any failure (git missing, not a
    repo, whatever) - a build must never fail because of the stamp."""
    try:
        out = subprocess.check_output(
            ("git",) + args, cwd=PROJECT_DIR, stderr=subprocess.DEVNULL
        )
    except Exception:
        return ""
    return out.decode("utf-8", "replace").strip()


def build_stamp():
    stamp = time.strftime("%Y-%m-%d %H:%M:%S UTC", time.gmtime())
    revision = git("rev-parse", "--short", "HEAD")
    if revision:
        if git("status", "--porcelain"):
            revision += "-dirty"
        stamp += " (%s)" % revision
    # Goes into a JSON string built by a writer that deliberately does no
    # escaping (see solar_control.cpp's s_json_body comment), and into a C
    # string literal here - so keep it plain ASCII with no quotes/backslashes.
    return "".join(c for c in stamp if 0x20 <= ord(c) < 0x7F and c not in '"\\')


def main():
    content = TEMPLATE.format(stamp=build_stamp())
    os.makedirs(os.path.dirname(STAMP_FILE), exist_ok=True)
    with open(STAMP_FILE, "w") as f:
        f.write(content)


main()
